version: "3"

services:
  minecraft:
    image: itzg/minecraft-server
    volumes:
      - ./world:/data/world
      - ./world_nether:/data/world_nether
      - ./world_the_end:/data/world_the_end
      - ./plugins:/data/plugins
      - ./server-icon.png:/data/server-icon.png
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.20.4"
      OPS: "swamp4frog"
      MOTD: "I'm not gay but $20 is $20..."
      ENABLE_WHITELIST: "TRUE"
      ENFORCE_WHITELIST: "TRUE"
      MEMORY: "5G"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 6G